### ISSUE TITLE
I can't run AppHide on Arch Linux

### ISSUE THREAD

**Issue by TomaszGasior** [willforde/AppHide#3]
Ofc I have dependencies installed. This error is printed in console.

```
./apphide:141: DeprecationWarning: Gtk.Widget.set_margin_right is deprecated
  iner_box.set_margin_right(16)
./apphide:142: DeprecationWarning: Gtk.Widget.set_margin_left is deprecated
  iner_box.set_margin_left(16)
Traceback (most recent call last):
  File "./apphide", line 74, in do_activate
    self.window = AppHideWin(application=self, title="AppHide")
  File "./apphide", line 153, in __init__
    xdg_apps = get_xdg_apps()
  File "./apphide", line 425, in get_xdg_apps
    xdg_data = XDGManager(app_files)
  File "./apphide", line 452, in __init__
    self.cleanup()
  File "./apphide", line 463, in cleanup
    if self.user_files and not self.system_files and self.user_files[0] in self.tracker:
  File "./apphide", line 458, in tracker
    XDGManager._tracker = Tracker()
  File "./apphide", line 333, in __init__
    self.cleanup()
  File "./apphide", line 387, in cleanup
    for filepath in self._hashes.keys():
RuntimeError: dictionary changed size during iteration
```

**Comment by TomaszGasior** [comment]
I did some tests and I found two reasons why I have this issue.

# 1. Removed application

I installed pamac-aur, graphical package manager for Arch Linux & Manjaro. Then, I hid two icons of that package manager using AppHide. Then, I uninstalled pamac-aur from my system but not-working activators were kept in ~/.local/share/applications causing AppMenu to crash on start.

# 2. Symlink

Epiphany (GNOME web browser) is able to create standalone application from website. As part of this process Epiphany creates symlink to its own generated desktop file from its own ~/.config/epiphany-blahblah to ~/.local/share/applications. Symlink casues crash in AppHide too.
